// APP
export const SET_NAVBAR_STATE = 'SET_NAVBAR_STATE';

// AVATAR
export const SET_CURRENT_AVATAR = 'SET_CURRENT_AVATAR';

// AUTH
export const NO_SIGNEDIN_USER = 'NO_SIGNEDIN_USER';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const RESET_SERVER_MESSAGES = 'RESET_SERVER_MESSAGES';
export const SERVER_ERROR = 'SERVER_ERROR';
export const SERVER_MESSAGE = 'SERVER_MESSAGE';
export const SET_SIGNEDIN_USER = 'SET_SIGNEDIN_USER';
export const USER_WAS_VERIFIED = 'USER_WAS_VERIFIED';
export const UNAUTH_USER = 'UNAUTH_USER';

// DASHBOARD
export const SET_DASHBOARD_DATA = 'SET_DASHBOARD_DATA';

// MESSAGES
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_INITIAL_MESSAGES = 'SET_INITIAL_MESSAGES';
export const SET_INITIAL_MESSAGECOUNTS = 'SET_INITIAL_MESSAGECOUNTS';

// NOTIFICATIONS
export const FILTER_NOTIFICATIONS = 'FILTER_NOTIFICATIONS';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';

// PLANS
export const SET_ACTIVE_PLANS = 'SET_ACTIVE_PLANS';
export const SET_INACTIVE_PLANS = 'SET_INACTIVE_PLANS';
export const SET_INITIAL_PLANS = 'SET_INITIAL_PLANS';
export const SET_INITIAL_PLANCOUNTS = 'SET_INITIAL_PLANCOUNTS';

// PROMOS
export const APPLY_PROMO_CODE = 'APPLY_PROMO_CODE';
export const FORM_PROMO_CODE = 'FORM_PROMO_CODE';
export const SET_ACTIVE_PROMOS = 'SET_ACTIVE_PROMOS';
export const SET_INACTIVE_PROMOS = 'SET_INACTIVE_PROMOS';
export const SET_INITIAL_PROMOS = 'SET_INITIAL_PROMOS';
export const SET_INITIAL_PROMOCOUNTS = 'SET_INITIAL_PROMOCOUNTS';

// SUBS
export const SET_ACTIVE_SUBS = 'SET_ACTIVE_SUBS';
export const SET_INACTIVE_SUBS = 'SET_INACTIVE_SUBS';
export const SET_INITIAL_SUBS = 'SET_INITIAL_SUBS';
export const SET_INITIAL_SUBCOUNTS = 'SET_INITIAL_SUBCOUNTS';

// TEMPLATES
export const SET_ACTIVE_TEMPLATES = 'SET_ACTIVE_TEMPLATES';
export const SET_INACTIVE_TEMPLATES = 'SET_INACTIVE_TEMPLATES';
export const SET_INITIAL_TEMPLATES = 'SET_INITIAL_TEMPLATES';
export const SET_INITIAL_TEMPLATECOUNTS = 'SET_INITIAL_TEMPLATECOUNTS';

// TRANSACTIONS
export const SET_CHARGES = 'SET_CHARGES';
export const SET_REFUNDS = 'SET_REFUNDS';
export const SET_INITIAL_TRANSACTIONS = 'SET_INITIAL_TRANSACTIONS';
export const SET_INITIAL_TRANSACTIONCOUNTS = 'SET_INITIAL_TRANSACTIONCOUNTS';

// REDUX FORMS
export const SET_BILLING_FORM_VALUES = 'SET_BILLING_FORM_VALUES';
