// AUTH
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const FETCHING_USER = 'FETCHING_USER';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const RESET_SERVER_MESSAGES = 'RESET_SERVER_MESSAGES';
export const SERVER_ERROR = 'SERVER_ERROR';
export const SERVER_MESSAGE = 'SERVER_MESSAGE';
export const SET_SIGNEDIN_USER = 'SET_SIGNEDIN_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

// PLANS
export const SET_ACTIVE_PLANS = 'SET_ACTIVE_PLANS';
export const SET_INACTIVE_PLANS = 'SET_INACTIVE_PLANS';
export const SET_INITIAL_PLANS = 'SET_INITIAL_PLANS';
export const SET_INITIAL_PLANCOUNTS = 'SET_INITIAL_PLANCOUNTS';

// PROMOS
export const SET_ACTIVE_PROMOS = 'SET_ACTIVE_PROMOS';
export const SET_INACTIVE_PROMOS = 'SET_INACTIVE_PROMOS';
export const SET_INITIAL_PROMOS = 'SET_INITIAL_PROMOS';
export const SET_INITIAL_PROMOCOUNTS = 'SET_INITIAL_PROMOCOUNTS';

// SUBS
export const SET_ACTIVE_SUBS = 'SET_ACTIVE_SUBS';
export const SET_INACTIVE_SUBS = 'SET_INACTIVE_SUBS';
export const SET_INITIAL_SUBS = 'SET_INITIAL_SUBS';
export const SET_INITIAL_SUBCOUNTS = 'SET_INITIAL_SUBCOUNTS';

// TRANSACTIONS
export const SET_CHARGES = 'SET_CHARGES';
export const SET_REFUNDS = 'SET_REFUNDS';
export const SET_INITIAL_TRANSACTIONS = 'SET_INITIAL_TRANSACTIONS';
export const SET_INITIAL_TRANSACTIONCOUNTS = 'SET_INITIAL_TRANSACTIONCOUNTS';

// REDUX FORMS
export const SET_BILLING_FORM_VALUES ='SET_BILLING_FORM_VALUES';
