export const AUTH_ERROR = 'AUTH_ERROR',
	AUTH_SUCCESS = 'AUTH_SUCCESS',
	FETCHING_USER = 'FETCHING_USER',
	RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS',
	SET_SIGNEDIN_USER = 'SET_SIGNEDIN_USER',
	SET_BILLING_FORM_VALUES ='SET_BILLING_FORM_VALUES',
	UNAUTH_USER = 'UNAUTH_USER';
