export const AUTH_ERROR = 'AUTH_ERROR',
	AUTH_SUCCESS = 'AUTH_SUCCESS',
	FETCHING_USER = 'FETCHING_USER',
	RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS',
	SAVE_FORM_INFO = 'SAVE_FORM_INFO',
	SET_SIGNEDIN_USER = 'SET_SIGNEDIN_USER',
	UNAUTH_USER = 'UNAUTH_USER';
